### ISSUE TITLE
Old projects compatibility of 1.5.1?

### ISSUE THREAD

**Issue by YouDevIt** [AGPX/C64GameMaker#3]
Ciao, ho provato a compilare il progetto in corso (Lunar Lander) e ottengo questo errore. Naturalmente il progetto Multiplexer funziona benissimo. Davvero complimenti! (Tra poco esce il video)

Code generated successfully.
Error during the process of compilation:
C:/Users/User/AppData/Local/Temp/LunarLander_PAL.cpp:3164:7: error: use of undeclared identifier '__keepOnTop__'
 3164 |                 if (__keepOnTop__ == __sprN__) { __keepOnTop__ = nullptr; }
      |                     ^
C:/Users/User/AppData/Local/Temp/LunarLander_PAL.cpp:3164:36: error: use of undeclared identifier '__keepOnTop__'
 3164 |                 if (__keepOnTop__ == __sprN__) { __keepOnTop__ = nullptr; }
      |                                                  ^
2 errors generated.

**Comment by AGPX** [comment]
Salve, risolto nella 1.5.2.

**Comment by YouDevIt** [comment]
Ciao! Ho scaricato la 1.5.2, ma purtroppo l'antivirus di Windows mi mostra il messaggio che ti allego e mi cancella l'eseguibile. Immagino che sia un falso positivo, però chiedo conferma prima di disabilitare l'antivirus sulla cartella del programma.

   Scusa per tutti questi problemi che ho con il Game Maker.
   Da "AGPX" ***@***.***
   A "AGPX/C64GameMaker" ***@***.***
   Cc "YouDevIt" ***@***.***,"Author" ***@***.***
   Data Mon, 23 Dec 2024 09:17:36 -0800
   Oggetto Re: [AGPX/C64GameMaker] Old projects compatibility of 1.5.1? (Issue #3)

   Salve, risolto nella 1.5.2.
